[Preferences]
   OverridableConfigTomlValues = [
       { File = "config.toml", Path = "WebServerAntiflood.SimultaneousRequests", Value = "256" },
       { File = "config.toml", Path = "WebServerAntiflood.TrieOperationsDeadlineMilliseconds", Value = "300000" }
   ]
